#!/bin/sh

# WIN=$(xdotool getactivewindow getwindowname)

# if [ ${#WIN} -gt 60 ]; then
#     WIN=$(echo $WIN | cut -c 1-60)
#     echo "$WIN..."
# else
#     echo $WIN
# fi


  ID=$(xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}')
  if [[ $1 ]] 
  then
    TITLE=$(xprop -id $ID -len $1 | awk '/_NET_WM_NAME/{$1=$2="";print}' | cut -d'"' -f2)
    echo " $TITLE "
  else
    TITLE=$(xprop -id $ID | awk '/_NET_WM_NAME/{$1=$2="";print}' | cut -d'"' -f2)
    echo " $TITLE "
  fi
